labels = [
"Background",
"Left To Annotate",
"Muscles",
"Fat",
"Abdominal Tissue",
"Mediastinal Tissue",
"Esophagus",
"Stomach",
"Small Bowel",
"Duodenum",
"Colon",
"Gallbladder",
"Liver",
"Pancreas",
"Kidney Left",
"Kidney Right",
"Bladder",
"Gonads",
"Prostate",
"Uterocervix",
"Uterus",
"Breast Left",
"Breast Right",
"Spinal Canal",
"Brain",
"Spleen",
"Adrenal Gland Left",
"Adrenal Gland Right",
"Thyroid Left",
"Thyroid Right",
"Thymus",
"Gluteus Maximus Left",
"Gluteus Maximus Right",
"Gluteus Medius Left",
"Gluteus Medius Right",
"Gluteus Minimus Left",
"Gluteus Minimus Right",
"Iliopsoas Left",
"Iliopsoas Right",
"Autochthon Left",
"Autochthon Right",
"Skin",
"Vertebra C1",
"Vertebra C2",
"Vertebra C3",
"Vertebra C4",
"Vertebra C5",
"Vertebra C6",
"Vertebra C7",
"Vertebra T1",
"Vertebra T2",
"Vertebra T3",
"Vertebra T4",
"Vertebra T5",
"Vertebra T6",
"Vertebra T7",
"Vertebra T8",
"Vertebra T9",
"Vertebra T10",
"Vertebra T11",
"Vertebra T12",
"Vertebra L1",
"Vertebra L2",
"Vertebra L3",
"Vertebra L4",
"Vertebra L5",
"Costa 1 Left",
"Costa 1 Right",
"Costa 2 Left",
"Costa 2 Right",
"Costa 3 Left",
"Costa 3 Right",
"Costa 4 Left",
"Costa 4 Right",
"Costa 5 Left",
"Costa 5 Right",
"Costa 6 Left",
"Costa 6 Right",
"Costa 7 Left",
"Costa 7 Right",
"Costa 8 Left",
"Costa 8 Right",
"Costa 9 Left",
"Costa 9 Right",
"Costa 10 Left",
"Costa 10 Right",
"Costa 11 Left",
"Costa 11 Right",
"Costa 12 Left",
"Costa 12 Right",
"Rib Cartilage",
"Sternum Corpus",
"Clavicula Left",
"Clavicula Right",
"Scapula Left",
"Scapula Right",
"Humerus Left",
"Humerus Right",
"Skull",
"Hip Left",
"Hip Right",
"Sacrum",
"Femur Left",
"Femur Right",
"Heart",
"Heart Atrium Left",
"Heart Tissue",
"Heart Atrium Right",
"Heart Myocardium",
"Heart Ventricle Left",
"Heart Ventricle Right",
"Iliac Artery Left",
"Iliac Artery Right",
"Aorta",
"Iliac Vena Left",
"Iliac Vena Right",
"Inferior Vena Cava",
"Portal Vein And Splenic Vein",
"Celiac Trunk",
"Lung Lower Lobe Left",
"Lung Upper Lobe Left",
"Lung Lower Lobe Right",
"Lung Middle Lobe Right",
"Lung Upper Lobe Right",
"Bronchie",
"Trachea",
"Pulmonary Artery",
"Cheek Left",
"Cheek Right",
"Eyeball Left",
"Eyeball Right",
"Nasal Cavity",
"Artery Commoncarotid Right",
"Artery Commoncarotid Left",
"Sternum Manubrium",
"Artery Internalcarotid Right",
"Artery Internalcarotid Left",
"Ijv Right",
"Ijv Left",
"Artery Brachiocephalic",
"Vein Brachiocephalic Right",
"Vein Brachiocephalic Left",
"Artery Subclavian Right",
"Artery Subclavian Left"
]
labels.insert(11, "Placeholder_for_missing_label_11")